apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: registryhostname:5000/imagename:tag
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
