apiVersion: v1
kind: Service
metadata:
  name: collector-service
  labels:
    run: collector-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30031
  selector:
    app: collector
